providers = ["python", "node"]

[phases.setup]
nixPkgs = ["python311", "nodejs_18"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["pip3 install -r requirements.txt"]

[start]
cmd = "./start.sh"
